const userActionTypes = {
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  LOG_OUT_USER_START: "LOG_OUT_USER_START",
  LOG_OUT_USER_SUCCESS: "LOG_OUT_USER_SUCCESS",
  LOG_OUT_USER_FAILURE: "LOG_OUT_USER_FAILURE"
};

export default userActionTypes;